name: Build and Deploy LaTeX Document

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Compile the LaTeX document
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          work_in_root_file_dir: true

      # Deploy the compiled PDF to GitHub Pages
      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }} # Points to the temporary GitHub Actions environment
          destination_dir: . # Leave root directory in gh-pages
