name: Build and Deploy LaTeX Document

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Compile the LaTeX document
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          work_in_root_file_dir: true

      # Checkout gh-pages branch
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      # Copy the compiled PDF to the gh-pages branch
      - name: Copy compiled PDF to gh-pages
        run: |
          cp main.pdf gh-pages/

      # Commit and push the changes to gh-pages
      - name: Commit and push PDF to gh-pages
        run: |
          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add main.pdf
          git commit -m "Deploy compiled PDF"
          git push
