name: Compile LaTeX and Deploy PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy PDF
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up LaTeX environment
      - name: Set up TeX Live
        uses: dante-ev/latex-action@v2
        with:
          packages: >-
            latexmk
            texlive-latex-extra
            texlive-fonts-recommended

      # Compile the LaTeX document
      - name: Compile LaTeX to PDF
        run: latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex

      # Deploy the PDF to GitHub Pages
      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Location of the compiled PDF
          destination_dir: pdfs/  # Optional: Store PDFs in a subdirectory
